src = files(
  'Algebra.F90',
  'Fields.f90',
  'Bond_Boost.f90',
  'Checkpoint.F90',
  'CLInterpreter.F90',
  'Constants.F90',
  'CVS.F90',
  'DDDA.F90',
  'Elements.F90',
  'Errors.f90',
  'ForceField.F90',
  'Hyperdinamics.f90',
  'Input_Parsing.F90',
  'Inq_Properties.F90',
  'Integration.F90',
  'Interaction.f90',
  'Pairs.F90',
  'Bias.f90',
  'Main.F90',
  'Metadynamics.f90',
  'MPI.F90',
  'NEB.f90',
  'Neighbor.F90',
  'Cells.F90',
  'Output.F90',
  'Programs.f90',
  'Program_Types.F90',
  'Groups.F90',
  'Graphs.F90',
  'Calc.F90',
  'Quasi_Newton.f90',
  'Select_Create.F90',
  'Set_Properties.f90',
  'Strings.f90',
  'Tables.f90',
  'TB.F90',
  'Variables.F90',
  )

executable('gems', 
  src,
  sprng_src,
  dependencies: [fpt_dep, fparser_dep],
  install: true,
  fortran_args: ['-DDIM3']
  )

